### ISSUE TITLE
leave Rinkeby addresses here

### ISSUE THREAD

**Issue by SCBuergel** [validitylabs/EthDapp-Boilerplate#1]

**Comment by lfrei** [comment]
0xa206660c7aB7B739745ebE2d529a25bf2Ca39fE6

**Comment by gitu** [comment]
0x0BBc8231790eC51F763384b5dDF142d500A01cdA

**Comment by cryptopat** [comment]
0x9242739F1DC8F032205e12fba5638634f3392D1e

**Comment by urswalde** [comment]
0x337529f40333E6e190Ec11A1B5FE7c67a4CeD2DA

**Comment by ybischof** [comment]
0xb98E44C58F81911023A3d4130E8f6C4B9E1F6532

**Comment by Karppa65** [comment]
0x8EAB84939Fa9BA39cdb3fCAbDFdFD7EA1cED9F77

**Comment by retoreber** [comment]
0xC563E209Cc5Dc58916450094fCEeD20c34b3195b

**Comment by chbuehler2709** [comment]
0x4E716FC0829D3B1C63a54a1940BEC0262fedc434

**Comment by block1212** [comment]
0x5d63e85ff03D71807755112CB63F1eF2A737352B

**Comment by b033153** [comment]
0xE6E64c1EE8cf675153E3c74461245c041AE108C6
