### ISSUE TITLE
本地运行会出现错误

### ISSUE THREAD

**Issue by jsliu27** [validitylabs/EthDapp-Boilerplate#3]
I doesn't has web3 :( Please open in Google Chrome Browser and install the Metamask extension.

**Comment by TankRyze** [comment]
部署到线上是可以的

**Comment by TankRyze** [comment]
> I doesn't has web3 :( Please open in Google Chrome Browser and install the Metamask extension.

部署到线上就可以了

**Comment by TankRyze** [comment]
closes #1

**Comment by TankRyze** [comment]
线上就可以了

**Comment by jsliu27** [comment]
> I doesn't has web3 :( Please open in Google Chrome Browser and install the Metamask extension.

线上就可以了
